#!/bin/bash -x
set -e
MYSQL_CLUSTERDB="$MYSQL $MYSQL_CLUSTERDB_OPTS $CLUSTERDB_NAME"

mysql $MYSQL_CLUSTERDB_OPTS -e "drop database if exists $CLUSTERDB_NAME; create database $CLUSTERDB_NAME"
cat $CLUSTERDB_SCHEMA | perl -p -e "s/NDB/$CLUSTERDB_ENGINE/" | $MYSQL_CLUSTERDB
script/load_genome_summary.py $LOAD_GENOME_SUMMARY_OPTS $MYSQL_CLUSTERDB_OPTS $CLUSTERDB_NAME $CLUSTERDB_FILE
